### ISSUE TITLE
Window resize is weird with the form

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#10]
Robin found this:

1) https://acteng.github.io/atip/areas.html?authority=West%20of%20England%20Combined%20Authority#12.1/51.45411/-2.5243
2) Resize your browser window
3) Open a form
4) Hide the sidebar

![Screenshot from 2022-10-24 15-34-43](https://user-images.githubusercontent.com/1664407/197552245-2aefeae7-d186-4546-bc20-00bb12fec6f8.png)

It happens even if the window is full width, but not full height. As soon as I maximize, it's fixed

**Comment by dabreegster** [comment]
Still happens, I haven't looked into this yet

**Comment by Robinlovelace** [comment]
Ah OK, apols. I thought that because the forms are so much smaller it was no longer and issue. Thanks for reopening it!

**Comment by Robinlovelace** [comment]
In think this is done now with the new design.

**Comment by dabreegster** [comment]
It's still not :( Even though we don't have a bottom bar, if you resize the window and expand/collapse the sidebar, some combinations cause the content of the sidebar to be visible on top of the bar when it shouldn't be

**Comment by dabreegster** [comment]
No resize bugs right now that I can spot, after we got rid of Carbon
