### ISSUE TITLE
`"Input data given to 'hover' is not a valid GeoJSON object."` error in console when using polygon tool

### ISSUE THREAD

**Issue by Sparrow0hawk** [acteng/atip#106]
I've been playing with the latest version of atip on `main` and find I now get the following error in the console when creating a polygon over streets using the Polygon tool:

```error
Object { message: "Input data given to 'hover' is not a valid GeoJSON object.", stack: "" }
```
https://user-images.githubusercontent.com/20887250/229308825-6e00a93d-a1d6-4e44-8a55-db1361cb8bcb.mov

This doesn't appear to have any effects UX wise and imagine might just add another reason to wanting to switch away from maplibre-gl-draw.

The cause of this has been introduced in ff78cb1 as errors don't occur in 0743de5, although its tricky to see what exactly has caused this error to appear.

We seem to be catching this [error](https://github.com/maplibre/maplibre-gl-js/blob/3157c340e5573699e46ce4b3fc17e9e670442e1a/src/source/geojson_worker_source.ts#L147) in maplibre-gl-js

**Comment by dabreegster** [comment]
Ah, thank you for catching this! I didn't spot during my testing, possibly because it doesn't seem to break anything, just log. If I had to guess, while we're in the middle of drawing a polygon, the new hover layer is trying to calculate and set the hover state, but probably passing along `null` or something, which isn't valid GeoJSON. I can look into it tonight or tomorrow.

**Comment by dabreegster** [comment]
And in the big new branch I'm working on, we can control this kind of thing much more clearly by guarding all of our event handling based on the current mode (select to edit form, select to edit geometry, drawing point, drawing polygon, drawing route): https://github.com/acteng/atip/blob/d9954ae260916e8e49876c01063a3c9e5756efa2/components/draw/SelectMode.svelte#L13

**Comment by Sparrow0hawk** [comment]
That looks good and I think you're right about whats causing the error.

Again, I don't think this is super urgent, especially as you're in the process of a bit rewrite of how lots of these tools work, just wanted to flag.

**Comment by dabreegster** [comment]
This doesn't occur on github `main` anymore to my knowledge, so closing
