### ISSUE TITLE
Add Streetview convenience

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#111]
Embed or open in another tab easily. Bing, Google, Mapillary, anything else

**Comment by dabreegster** [comment]
I don't think we're allowed to embed Streetview directly. https://cloud.google.com/maps-platform/terms:

> No Use With Non-Google Maps. To avoid quality issues and/or brand confusion, Customer will not use the Google Maps Core Services with or near a non-Google Map in a Customer Application. For example, Customer will not (i) display or use Places content on a non-Google map, (ii) display Street View imagery and non-Google maps on the same screen, or (iii) link a Google Map to non-Google Maps content or a non-Google map.

But maybe we're allowed to have a link that opens a new tab

**Comment by robinlovelace-ate** [comment]
Sounds reasonable.

**Comment by dabreegster** [comment]
Someone requested a QGIS plugin-style where you can just click the map and open a new tab
