### ISSUE TITLE
Route tool button should be the same size/prominence as the other buttons

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#113]
As shown here: 

![image](https://user-images.githubusercontent.com/1825120/229798474-99fe1af3-0b1f-4891-a892-2096eda69f31.png)

**Comment by robinlovelace-ate** [comment]
For completeness, here is the new route tool button in all it's consistently-styled glory.

![image](https://user-images.githubusercontent.com/122299965/233829877-5b7a01b5-865b-446d-b309-6ca7cbab8300.png)

One thing occurs to me on looking at this with fresh eyes: the whole right-hand box is relatively huge. Would it be easy to try scaling the box and its contents down a bit @dabreegster ?

**Comment by dabreegster** [comment]
Scaling things down is easy to try. Opened #134 to discuss other design changes
