### ISSUE TITLE
Polygon snapping?

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#118]
There are three main options:

option 1: broadly, like the existing route snapping, but as soon as you have 3 points, it connects the first and last. You can no longer click normally to add a totally new point, just drag existing points to make new waypoints

option 2: like route snapper, but some button to say "close it off and make an area". then you can only drag to adjust

option 3: make it more like the current polygon tool, where a click will insert a vertex in the nearest line segment. like that, but try to snap

Which to go for? Comments below welcome (requires signing up for a GitHub account).

Previous outdated comment below.

<details>

~~Worth implementing? I know it would be of use to the spatial planning team although they may be looking for a non OSM source of snap points. It could be handy when planning traffic management areas but not sure. So pitching as a question.~~

**Comment by dabreegster** [comment]
Prototype at https://github.com/dabreegster/route_snapper/tree/cordon. We can feed it any line-strings we want, if there's a desire for non-OSM based

**Comment by robinlovelace-ate** [comment]
Ace. I tentatively suggest this is part of the v2 road map.

**Comment by robinlovelace-ate** [comment]
Have set it to v2. We can always revisit.

**Comment by dabreegster** [comment]
This is working, with no urgent next steps known. https://github.com/dabreegster/route_snapper/issues/27 has improvements
