### ISSUE TITLE
Route splitting

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#119]
This UI feature will allow people to split routes into sections that correspond to lengths that have the same cross section, as described in CAD diagrams or tools like StreetMix: https://streetmix.net

Started in https://github.com/acteng/atip/pull/114

**Comment by dabreegster** [comment]
- [ ] Scissor icon for split tool
- [ ] Unit tests
- [ ] Move splitting logic to route-snapper
- [ ] Automatically update/set the name for split segments. And/or group the split segments together.

**Comment by dabreegster** [comment]
This could still use a change in implementation and some unit testing, but the feature is working for v2, so calling it done and tracking further work in https://github.com/dabreegster/route_snapper/issues/32
