### ISSUE TITLE
Auto-derive the form from a data schema

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#13]
If we settle on some way of describing per-intervention data, we ought to be able to auto-generate the HTML form from it. I'm totally unfamiliar with the space of JS libraries that do this sort of thing, but I'll buy and eat several hats if nobody's made this kind of thing before

**Comment by Robinlovelace** [comment]
Could this way work? Seems to be popular and fairly well established: https://json-editor.github.io/json-editor/

**Comment by Robinlovelace** [comment]
Minimal demo: https://acteng.github.io/schema/json-editor/schema-minimal-demo.html

That html was derived from this file: https://github.com/acteng/schema/blob/main/json-editor/schema-minimal-demo.json
