### ISSUE TITLE
Handle incorrect App parameters

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#131]
We get `authorityName` from URL params and require it to match something in `assets/authorities.geojson`. Near
https://github.com/acteng/atip/blob/9bd25471db3470553015c1dd3f0d9a0fd5be0294/src/App.svelte#L29 we insist everything exists and is fine, but we should cleanly handle problems with an error message/page or auto-changing to some default

Leaving this open as a good starter bug for Svelte

**Comment by ELBuenFercho** [comment]
Hello ! I'll do my best to work on it, thanks  (is it necessary to assign it to myself?) thanks !!!

**Comment by dabreegster** [comment]
Awesome! Happy to chat over Slack/Teams/etc about if you like. First we should decide how to handle the error (what we show to the user), then can implement it and write a Playwright test for it

**Comment by robinlovelace-ate** [comment]
Testing this with the following link: https://acteng.github.io/atip/scheme.html?authority=nonexistentauthority#10.91/50.6717/-1.3282

**Comment by robinlovelace-ate** [comment]
This is what I see, what's wrong with this from user perspective? 

![image](https://github.com/acteng/atip/assets/122299965/09f55f3d-4c4b-4fda-9484-371a8d42caf3)

**Comment by Pete-Y-CS** [comment]
I guess we'd want to redirect to the select authority page and display an error 
> the authority requested does not exist

**Comment by dabreegster** [comment]
Sounds good to me. You reckon we show the error first, then redirect? Or the other way around? Maybe something like a modal that says the error, isn't closeable by clicking away, then only has one button to "go back and try again" or something?

**Comment by Pete-Y-CS** [comment]
Good question. I was thinking redirect and show the error on the select authority because I guess it's kinda where they need to know there was an error in this case: they need to know to select a predefined authority

**Comment by dabreegster** [comment]
That sounds sensible to me. Just thinking through the implementation of that a bit... using a query param to plumb the incorrect authority name?

Probably the most common way of arriving in this error state right now is from the scheme browse page, because we haven't yet correctly retained the authority field from the original GJ input files when merging. Redirecting to the homepage in that case doesn't make sense, but it'd be simpler to just detect the error there, display a warning, and stay on the page.

**Comment by Pete-Y-CS** [comment]
Hmm good point. I had planned on using a query param (in fact it's already done: 
![image](https://github.com/acteng/atip/assets/133757676/9ff66b09-85b6-4782-8c01-db7a7b8691bc)
)

But that doesn't really resolve this issue if we can get to app.svelte from multiple places..

**Comment by dabreegster** [comment]
I think this approach is fine. (I'd plumb through the name to display it, ideally)

I can think of a few ways of getting to this error state:
- accidentally copying a URL wrong (solved by this approach)
- uploading a GJ file with something bad on the front page. currently it does `window.alert` with `Unknown authority`. Per https://design-system.service.gov.uk/components/file-upload/, we should switch that to showing error text instead
- clicking something from the browse page

I think all 3 require slightly different answers, and we could fix em one at a time
