### ISSUE TITLE
Specialize ATIP for planning

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#136]
Specialize ATIP for land use planning applications. The changes needed are:

- #118 
- color the polygons to match a type:  preapp / outline / reserved matters / local plan
- Assuming we don't need linear routes or points, we can maybe simplify the toolbox.
- Change the form to instead have:
  - ATE reference type
  - application type (the thing we're coloring?)
  - Number of Units / Floorspace (GFA) / Area (ha)
  - ATE Triage / Prioritisation: No Comment / Standing Advice / Toolkit Assessment
  - ATE Recommendation: No Comment / No Objection / Standing Advice / Deferral / Approve subject to conditions and/or obligations / Refusal
- Depending on how this form looks, maybe this is also a forcing function to try a full-screen or larger modal for the form contents, instead of the sidebar.

How should we implement this? My strawman proposal is to have a separate `/planning_scheme.html` page glued to a variation of `App.svelte` (a copy or we parameterize it)? We should be able to directly plug in most components, or parameterize things to handle the current ATIP form or the other.

**Comment by robinlovelace-ate** [comment]
Good shout. I think this deserves its own milestone as separate from the core Design functionality.

**Comment by dabreegster** [comment]
Planning mode is live and has everything mentioned here, except for area snapping. Since there's an issue for that and no further info on what's needed here, closing

**Comment by robinlovelace-ate** [comment]
Latest on this shown in quick demo below. 


https://user-images.githubusercontent.com/122299965/234585002-905b4c71-92da-4271-acbf-ca5e805c4c95.mp4
