### ISSUE TITLE
Feature request: combine polygon tools into one (freehand and snapped)

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#159]
It would be great if the these two UI elements could be combined into a single New Polygon tool:

![image](https://github.com/acteng/atip/assets/122299965/a634719e-3b68-4cf6-a55c-1617150527e4)

In terms of UX user story:

- User wants to make a polygon
- Click on Polygon tool
- Woo it snaps!
- How do I put a freehand element where no roads?
- Aha tooltip or some other guidance that is visible but not intrusive tells me!
- Proceed to draw polygon, holding down Shift to draw points that are not on the network
- Job done :tada:

**Comment by dabreegster** [comment]
It took over a year, but done :) #549
