### ISSUE TITLE
Minor updates to fields based

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#16]
Building on this https://github.com/acteng/atip/commit/8533cefc0759574374487f26ddfaadc76118fd81 there are a couple more tweaks to make. https://acteng.github.io/schema/v1 isn't quite complete but has everything for the 'base fields' that do not change.

**Comment by Robinlovelace** [comment]
This difference: no Description field.

**Comment by dabreegster** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

**Comment by Robinlovelace** [comment]
To my surprise, it seems to have worked #18 without re-running the render local shell script, this is cool! 

![image](https://user-images.githubusercontent.com/1825120/198838133-3109a592-f6bd-4a54-9240-86261010b3b0.png)

**Comment by dabreegster** [comment]
Textarea. Description could be longer than one line.

And also on other two pages please

**Comment by Robinlovelace** [comment]
Will give it a bash :+1:
