### ISSUE TITLE
Minor feature request: change wording above drawing tools to be more generic or change them depending on the schema

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#160]
As shown below ATIP currently says "Click on an intervention" which is not right for reporting criticals

![image](https://github.com/acteng/atip/assets/122299965/f89105e9-d850-464d-b2a8-24f8bc4531bb)

Suggested text

> Click on a tool to document the location of a critical issue

(or similar)

**Comment by robinlovelace-ate** [comment]
Reproducible example: https://acteng.github.io/atip/scheme.html?authority=Isle+of+Wight&schema=criticals#14.72/50.63716/-1.40675

**Comment by dabreegster** [comment]
We use "intervention" in many places in both the code and user-visible app. "0 interventions" on the left, in the instructions, in the legend, etc.

Should we show a per-schema noun? For criticals, "critical issue." For planning, what should it be -- "planning application" or "application"?

Or should we aim for a kind of generic word and just say "object"?

**Comment by robinlovelace-ate** [comment]
> Or should we aim for a kind of generic word and just say "object"?

For now a generic word like object could be fine:

> Click an object to fill out its attributes 

works for all modes. :+1: to the suggested fix, good thinking, and will help reduce code complexity and number of lines of code, for now...

**Comment by robinlovelace-ate** [comment]
Reopening because we've had clear communication that Object is not good for the main use case. I suggest reverting this or making the word "Object" change depending on the mode.

**Comment by dabreegster** [comment]
So what specifically do we want to change it to? When the schema is v1/v2 (not criticals or planning), do we again use "intervention"?

For planning mode, maybe "development"?

For critical issue mode, maybe "issue"?

**Comment by robinlovelace-ate** [comment]
#256 has a fix for this I think.

**Comment by robinlovelace-ate** [comment]
> So what specifically do we want to change it to? When the schema is v1/v2 (not criticals or planning), do we again use "intervention"?

Yes for sure, that's what Lynsey and the inspections team wanted. In hindsight we shouldn't have changed it to 'object' in the first place, apologies for jumping the gun on that decision which we're now reverting.

> 
> For planning mode, maybe "development"?

Development is perfect

> 
> For critical issue mode, maybe "issue"?

I vote `Critical issue` to be specific.

**Comment by dabreegster** [comment]
Closed by the PR above
