### ISSUE TITLE
Consistent language in copy: intervention not scheme

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#17]
In https://acteng.github.io/schema/v1 changes are referred to as interventions. Scheme is also a commonly used term but I think Intervention may be better as it can cover a wider range of things and has fewer meanings.

**Comment by dabreegster** [comment]
IIUC we want to consistently say "intervention"

**Comment by Robinlovelace** [comment]
Yes. I can give that a bash, will self assign.
