### ISSUE TITLE
Loading a geojson file directly from a URL parameter

### ISSUE THREAD

**Issue by Sparrow0hawk** [acteng/atip#172]
A brief feature idea from a discussion today:

If we have a list of scheme .txt files, it would be nice to click a link that automatically opens ATIP with that .txt file loaded. 

## Considerations

- This would only work for public URLs 
- Is this even possible/practical
- How would this interact with existing data in local storage?
- Is there a better way to do this that isn't directly in the ATIP code base

**Comment by dabreegster** [comment]
We could support this pretty easily -- just `fetch` the file, then load it up same as https://github.com/acteng/atip/blob/41be5dbc720ffa6907391ff5cd9d41cc4850582e/src/lib/EntireScheme.svelte#L98.

> How would this interact with existing data in local storage?

It would blindly overwrite it, the same as clicking "Load file" and opening something locally. We may want to revisit that generally; right now local storage only keeps one file per (authority, schema) combo. But also, local storage has something like a 5MB limit per website, so ATIP power users are going to hit problems at some point! I'd love to figure out how to manage more / larger files generally, and have some kind of cloud-ish uploading/sharing.

**Comment by robinlovelace-ate** [comment]
Does this need to be documented? Great new feature, @becfleming-ate was asking about this so will be pleased I imagine!

**Comment by dabreegster** [comment]
Good point! https://github.com/acteng/atip#query-parameters
