### ISSUE TITLE
Create internal scheme overview page

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#173]
Internally, people are currently using an R-generated Leaflet viewer to look at all ATF4 schemes everywhere. There's been a request to be able to search by scheme name.

I actually didn't realize people are using the Leaflet viewer so much; I think we should move that functionality into ATIP proper to control it better. I propose a new page that has a map and a sidebar, but no drawing tools. It displays the consolidated GeoJSON file with simple styling, lists schemes (not individual interventions!) in the left sidebar, has a text search for scheme name, and makes it easy to click on a scheme and open ATIP edit mode with that file.

Biggest open question in my mind is how to give people the all-schemes GeoJSON file. Simplest answer is just to have a regular file loader on that page, send the big geojson file around using onedrive/sharepoint/whatever other internal thing.

Other open question is how to conveniently open ATIP with just that one scheme file after clicking.

**Comment by robinlovelace-ate** [comment]
+1 to that. What would the input into this new page be? Currently we have

- A folder with sub-folders containing ATIPs
- A zip file
- GeoJSON files created by R/Python scripts that read-in the ATIP data

**Comment by robinlovelace-ate** [comment]
Could there be a dedicated page for internal use with "load directory" that iterates through all .txt/.geojson files or am I missing something?

**Comment by dabreegster** [comment]
> +1 to that. What would the input into this new page be? Currently we have

I don't think it's easy to recursively read a bunch of files from a picker in the browser. Either one of the consolidated files (`atips_all_raw.geojson` or something else) or a zip, I'd say. Probably the first is easier, but it maybe depends what we want to do besides just displaying everything in one map.

> Could there be a dedicated page for internal use with "load directory" that iterates through all .txt/.geojson files or am I missing something?

That's what I'm suggesting. It doesn't need to be internal or anything, just a new page where you manually load a file representing a bunch of ATIP files all smushed together. The different schemes are somehow grouped/identified -- `atip_analysis` currently does it by adding some properties to every feature. We could also nest `FeatureCollections`. This is allowed by the GeoJSON schema, but possibly the support for it in MapLibre or other standard tools is less good, so maybe we avoid that. Not sure yet.

**Comment by robinlovelace-ate** [comment]
Sounds good. I think if the input can be the raw ATIPs (or other valid GeoJSON files without worrying much about attributes) that could be v. helpful.
