### ISSUE TITLE
Encourage/enable edits to OSM

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#179]
This is a meta issue split out from conversation in #177.

Need: OSM data is imperfect. The more users know about it and know how to edit it, and the more they actually edit it to improve it, the better ATIP data, and all evidence derived from OSM data, will be.

There are many options from simple to complex including:

- [ ] General message along the lines of "ATIP depends on good OSM data. Contribute at osm.org" could be in about page, would be great for it to be read by many.
- [ ] Links to OSM ways, e.g. as a tooltip when hovering over layers, as per https://github.com/acteng/atip/issues/177#issuecomment-1554334683
- [ ] OSM editing mode in ATIP as per https://github.com/acteng/atip/issues/177#issuecomment-1554334683 also

**Comment by robinlovelace-ate** [comment]
Tagging as v3 issue for now, with reference to the first two options. The third, if we decide to do it, is probably a bigger issue out of scope for v2. I think we could usefully mention OSM data with a link to https://osm.org in v2 though, maybe in the about page.

**Comment by dabreegster** [comment]
Ah no, closing as inactionable. We link to OSM from the About page in the sketch tool and on all relevant layers in the browse tool. There are much larger open questions about how to collect feedback from users about things they see that look wrong and validate that and funnel it back into OSM.

**Comment by robinlovelace-ate** [comment]
Aha. Just tested for one of the OSM layers in York. Great that it jumps to the relevant OSM way on that layer, it's a bit sudden and does not give warning. UX experience that I guess would be less surprising would be to click on an entity, see some info, including maybe 'View in OSM' and possibly streetview, and then explicitly have one more click. 

![image](https://github.com/acteng/atip/assets/122299965/2350f0da-1cda-4d82-8b62-ccab582c83eb)

**Comment by robinlovelace-ate** [comment]
Overall: agree re wider questions that need some thought.
