### ISSUE TITLE
Features table

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#189]
Idea: simple features table like the one below, but with fewer rows and columns.

Rows could include

- [ ] Points, line, polygons
- [ ] Routes snapped to network
- [ ] Polygons that snap to network
- [ ] Dynamic schemas
- [ ] Free to use
- [ ] Open source
- [ ] Outputs standard file format (should we switch to .geojson in dev version?)
- [ ] Allows data upload
- [ ] Keeps user date

Something like this is what I'm envisioning, maybe after v2 is complete and to be updated after each release?

![image](https://github.com/acteng/atip/assets/122299965/15060612-6132-4baf-8895-130cd1a4a524)

Source: https://github.com/SciML/DifferentialEquations.jl

**Comment by robinlovelace-ate** [comment]
Columns could include

- [ ] [Active Travel Map (giperspective.co.uk)](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.giperspective.co.uk%2Factive-travel-map%2F&data=05%7C01%7CRobin.Lovelace%40activetravelengland.gov.uk%7Ce329bd5258584b3498f408daf25aefee%7C28b782fb41e148eabfc3ad7558ce7136%7C0%7C0%7C638088769620459826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yd0eCv6h2HujKgoLSeSql1oGjkIdUFAeowgS6rVh6Xg%3D&reserved=0)
  - [Active Travel Map for South Dublin County Council - gi Perspective](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.giperspective.co.uk%2Fcase-study%2Factive-travel-map-for-south-dublin-county-council%2F&data=05%7C01%7CRobin.Lovelace%40activetravelengland.gov.uk%7Ce329bd5258584b3498f408daf25aefee%7C28b782fb41e148eabfc3ad7558ce7136%7C0%7C0%7C638088769620459826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p2FvlOwQomRwp%2Fyi3wmbJOroFAOkcJu80iKRHDhfBNY%3D&reserved=0)
- [Active Streets Assessment Tool](https://agilysis.co.uk/portfolio-item/active-streets-assessment-tool/)
- Remix
- ...

**Comment by dabreegster** [comment]
I don't think anyone's asking for something like this, and I don't understand the value. The example columns are kind of comparing apples and oranges mostly... if anything, comparing to geojson.io or Felt would make more sense.
