### ISSUE TITLE
Add more basemaps

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#205]
Currently we only have 2 basemaps.

I think basemaps that show a bit more detail on existing infrastructure could be good, e.g.:

- [ ] TransportMap which has good data on public transport routes: https://wiki.openstreetmap.org/wiki/Transport_Map
- [ ] CyclOSM: https://leaflet-extras.github.io/leaflet-providers/preview/#filter=CyclOSM

**Comment by dabreegster** [comment]
More basemaps would be great! I'd also love to find a more detailed satellite layer for the UK that we have a license to use.

Implementation notes:
- Right now we're wired to use maptiler styles: https://github.com/acteng/atip/blob/cbdd647ee4231975cbdb81628dbb3d0414f3aefe/src/lib/Map.svelte#L20. We can of course support more.
- Need to update map attribution text
- Need to make sure the layer order works with other sources: https://github.com/acteng/atip/blob/cbdd647ee4231975cbdb81628dbb3d0414f3aefe/src/maplibre_helpers.ts#L240
- All of our color scheme / design is mostly tuned (very loosely speaking!) for the default style, and looks bad with the satellite option. All of the colors/styling may need to change to reasonably fit other basemaps.

**Comment by dabreegster** [comment]
Closing old issue. We've got Google satellite now
