### ISSUE TITLE
Cannot add new objects, including points or freehand lines/polygons, if route loading fails

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#207]
Following #206 I tried sketching some objects that don't depend on routes to be loaded but failed. What I saw: 

![image](https://github.com/acteng/atip/assets/122299965/d915542b-6db6-4b44-8b5f-383b70b1188a)

Expected behaviour: clicking on New point would enable me to draw a new point.

Actual behaviour: I could not add any objects as far as I can tell.

**Comment by robinlovelace-ate** [comment]
Wider point: I think the app should 'fail gracefully' or even work with reduced features when route networks are unavailable.

**Comment by dabreegster** [comment]
I remember thinking about how to handle this near https://github.com/acteng/atip/pull/108#discussion_r1157447093. Agreed that we should fail gracefully.

We can start by writing a test that pretends loading the file fails: https://playwright.dev/docs/mock

**Comment by dabreegster** [comment]
`errors.spec.ts` verifies this works
