### ISSUE TITLE
Load the route snapper in a web worker

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#23]
Many perf improvements to the snap tool needed, but one short-term might be to do the initial load in a web worker. Otherwise the map loading will hang

**Comment by dabreegster** [comment]
https://stackoverflow.com/questions/44118600/web-workers-how-to-import-modules/45578811#45578811
I'm stuck here, Firefox still doesn't have support...

**Comment by dabreegster** [comment]
https://rustwasm.github.io/wasm-bindgen/examples/wasm-in-web-worker.html
Need `no-modules` and more workaround above

**Comment by dabreegster** [comment]
Argh, this is really annoying. I can do the expensive step of deserializing in a web worker, but the resulting JS/WASM magic blob can't be passed back to the main thread due to https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#transferring_data_to_and_from_workers_further_details

**Comment by Robinlovelace** [comment]
Seems to work fine for me on Firefox in any case.

**Comment by dabreegster** [comment]
https://acteng.github.io/atip/scheme.html?authority=Greater%20London#9.86/51.4737/-0.1634

Once the progress bar reaches the end (download is done), for me there's a noticeable ~13 second lag when you can't drag the map. We're deserializing and blocking the main thread. That's the problem I want to solve here

**Comment by Robinlovelace** [comment]
Sounds like a bonus feature, still faster than the PCT and all client side so not too shabby for the largest region we have.
