### ISSUE TITLE
Tie down schema

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#231]
A big part of v3 is switching to a schema that asks ATIP users to fill in specific bits of information such as path width depending on the type of scheme that is being added. According to the ATF guidance there are 11 (I think?) types of scheme: https://www.gov.uk/government/publications/how-to-complete-the-active-travel-fund-4-proforma/guidance-note-for-local-authorities-to-support-completion-of-the-active-travel-fund-4-proforma#monitoring-and-evaluation

Things that we need to tie down:

- [x] #242
- [ ] Feedback on the user interface and user experience from the inspectorate
- [ ] Identification of data needs not captured by the schema currently
- [ ] Identification of functionality in the schema that is not needed

We don't need to have a dropdown to select from one of those but we **do** need to be able to categorise schemes/interventions into one or more of those categories (are there more) from ATIP data. This issue is about the contents of the schema, currently

https://github.com/acteng/atip/blob/2d5893c4e341df4754c2e167966c47b122425c80/src/schemas/v2.json#L1-L153

@KitAllwinter was looking at this. We should iterate based on his feedback and then widen it out with an updated schema.

There's a wider issue about UI, but that's for another issue. Quickfire question @dabreegster is it easy to turn on the v2 schema briefly for testing? Currently only seeing V1, Critical Issues, Housing Developments issues.

**Comment by dabreegster** [comment]
> we do need to be able to categorise schemes/interventions into one or more of those categories

To check my understanding: we still likely want to capture more detailed information like the current v2 draft does, but whatever we collect, we need to map into things like high/medium/low complexity for one of those 11 categories?

> is it easy to turn on the v2 schema briefly for testing

Just append `&schema=v2` to the end of a URL to get there immediately. Enable https://github.com/acteng/atip/blob/2d5893c4e341df4754c2e167966c47b122425c80/src/pages/App.svelte#L109 to get it back in the list

**Comment by robinlovelace-ate** [comment]
Heads-up @acteng/atip-core I've just updated the original post with more clarity on what I think the ask is here. I do think this is a priority and, if we set up a meeting/workshop and focus on clear questions, I don't think it is a huge ask.

**Comment by dabreegster** [comment]
Closing old issues. We have a very simple v2 schema today, and there's a bigger discussion internally around the kinds of detail we need for infrastructure.
