### ISSUE TITLE
Infer missing speed limits

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#243]
The speed limit layer added in #169 is missing data, as described in the PR, discussed in #177, and visible clearly on any map.

I was considering integrating with https://github.com/westnordost/osm-legal-default-speeds to infer missing values, but currently, the [rules for GB](https://github.com/westnordost/osm-legal-default-speeds/blob/09d9b8aa3512abd9b2cdbfeab7e7bb56e16fb9b0/demo/distribution/legal_default_speeds.json#L3718), which seem to match https://www.gov.uk/speed-limits, do not seem to take effect. I plugged https://www.openstreetmap.org/way/74150037 as an example `highway=residential` in at https://westnordost.github.io/osm-legal-default-speeds/#tags=highway%3Dresidential&cc=GB, but it didn't match any rules.

Opening this issue to track all possible solutions. I would be in favor in the UI of having an option to only show explicitly-tagged-in-OSM speeds, but disabling and de-emphasizing by default.

**Comment by robinlovelace-ate** [comment]
Sounds good, I think residential being 30 or less is a good starting point and thumbs up to representing that in the UX.

**Comment by dabreegster** [comment]
We have more thorough data from OS now
