### ISSUE TITLE
Rethink autosaving while editing geometry

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#247]
With how ATIP works today, it's easy for the user to suddenly lose their work:

- if you draw a new polygon, but then click a different tool without saving, you completely lose the new polygon
- if you edit an existing route or polygon, but then click something in the sidebar or another tool, you lose the edits

We asked this question in https://github.com/acteng/atip/issues/142#issuecomment-1552820804, but never really answered it. I see a few options:

1) Silently throw away work when changing states. We mostly do this today.
2) Prompt the user to save or discard changes when they try to switch to a different mode.
3) Disable the ability to click buttons or things in the sidebar when we're drawing or editing geometry. #230 started going in this direction for the very simple case of saving/loading files.
4) Auto-save all geometry changes as the user makes them. When switching to another tool, changes are never lost.

After the UX session with Kelin, I'm more convinced that option 4 is the behavior that best matches expectations and how other tools usually work. This would mean when creating a new polygon or route, as soon as the geometry is valid (at least 2 or 3 points), we add a new object to the sidebar. Option 4 would make most sense when paired with a universal undo/redo function in ATIP, something we're headed towards anyway. That way if you click an object and accidentally adjust geometry, you can just Ctrl+Z.

**Comment by Pete-Y-CS** [comment]
I think autosave is a great idea. I have a slight concern that undo might be a prerequisite, or that we'll have to think very carefully about how we use autosave. 

It feels like it could be annoying to try changing a snapped route, finding it didn't do what you'd like, and not having a way to go back because it autosaved.

As for the specific options suggested, I quite like option 2, but not against 4 so long as we are sure we're gonna resolve undo

**Comment by Pete-Y-CS** [comment]
Caveat to above prefrences: 2 and 4 both seem fine to me but speaking to a UX person/users would be ideal

**Comment by dabreegster** [comment]
> It feels like it could be annoying to try changing a snapped route, finding it didn't do what you'd like, and not having a way to go back because it autosaved.

A "blunt" form of undo would be very easy. When you first start editing, we remember the original geometry, and if the user presses the existing "Cancel" button, we revert to that. The more granular undo would let you control each new waypoint, drag, etc while inside the tool, and outside a specific tool, reverse entirely new features or entire edits to features.

**Comment by Pete-Y-CS** [comment]
Maybe we have the blunt undo for now and granular undo later on, sounds like a great solution
