### ISSUE TITLE
Rethink edit attributes vs edit geometry mode

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#248]
#108 introduced two different modes, edit attributes (for stuff in the sidebar) and edit geometry (for the geospatial representation). The motivation was that the form was going to soon outgrow the sidebar and become a modal. A big modal would cover up the map, making it impossible to edit the geometry too.

I'd like to revisit that design choice, after the UX session with Kelin. I think one "Edit" mode (or "select" or some other name) is fine. Clicking or selecting an object would activate the appropriate controls on the map, but ALSO open up the form in the sidebar. If our forms ever outgrow the sidebar, we simply add a prominent button there to pop-out into a full modal and cover part/all of the map. If a user is trying to fill out this larger form for many objects, we can even have some kind of "sticky" behavior about showing that bigger modal by default or not.

Thoughts?

**Comment by robinlovelace-ate** [comment]
I don't fully understand the suggestion but my thinking is that, given that the attribute editing form will grow, it makes sense to keep geometry editing and attribute editing functionality separate.

**Comment by dabreegster** [comment]
Try a quick prototype at https://acteng.github.io/atip/merge_edit/scheme.html?authority=Adur (give it a few mins to deploy, and keep in mind there are lots of bugs left in this -- it's just a quick example)

https://github.com/acteng/atip/assets/1664407/eea6ece2-ad51-4985-a29f-f17b2e06ad37

Even in the current approach with a separate "Edit attributes", we're only using the sidebar. The idea with the new approach is that we'd add a new button to show a full-screen form:
![Screenshot from 2023-06-26 13-37-29](https://github.com/acteng/atip/assets/1664407/c4bad9f1-51e5-4986-8010-d56d4e7f277e)

I've seen a few people get confused by the two separate edit modes, and when using ATIP myself, it's a bit frustrating to switch back and forth.

**Comment by robinlovelace-ate** [comment]
Amazing progress Dustin! I'm in strategy mode but will aim to test soon.

**Comment by dabreegster** [comment]
Thanks Stuart! You've got me thinking about a few other old ideas for simplifying the UX flow... One note -- we don't have the ability (or any intended use case for this) to select multiple features at a time today.

Thinking through the UX again... this idea of a list and a focus view really sounds solid:

**List view**
- The left sidebar lists all features and has the file management / scheme-wide forms (possibly as a modal, if they grow to include more)
- The map shows all features
- Clicking one feature either from the sidebar or map switches into the focus view
- The current toolbox on the right changes to just have options for "New point / route / freehand polygon / snapped polygon". Or if we settle on a better taxonomy for what we want people to map, maybe more semantic categories (crossing, school street, junction improvement, side road treatment, etc) that launch the appropriate geometric tool.

**Focus view** on one existing feature at a time:
- The left sidebar is just the form for that one feature, with nothing else shown
- When first creating a new feature, maybe this form is disabled until the user has drawn enough geometry
- The right toolbox changes to only show map controls for the current geometry type. This will free up some visual room to be much more explicit about switching between freehand and snapped mode for route-drawing, for example.
- Other features in the map can be drawn faded out, and won't be selectable at all
- Prominent "Save", "Undo / revert", "Delete" buttons to change states back to the list view

I'm not entirely sure where something like the split route tool belongs. Probably as a possible mode when focusing on one existing route.

Any thoughts on this design? It'll be a substantial code change, and I'd prefer to not invest much in it without confidence this is nice. Would low-fi mockups be useful first? @robinlovelace-ate, any opinions on this big re-design?

**Comment by Robinlovelace** [comment]
Sounds good to me! Looking at the current ATIP Sketch tool (which this relates to more than browse tool):

Authority landing page

![image](https://github.com/acteng/atip/assets/1825120/d0c84f70-7595-4696-826f-c5387f102c21)

In edit mode, this will be better with New point / route / polygon (will be UX win if they can be merged, e.g. by making Shift -> freehand mode like the route tool which is working really nice now) on the right but no huge change right?

![image](https://github.com/acteng/atip/assets/1825120/7b8a93ed-5db6-4049-9c62-83255ed28989)

In list mode:

![image](https://github.com/acteng/atip/assets/1825120/c84dcc39-72a5-488a-aa8c-44e7b22c9f4e)

Agreed, there's TMI in the left panel which overflows. +1 to showing only one feature. Hope that's helpful..

**Comment by dabreegster** [comment]
Please try out https://acteng.github.io/atip/focus_mode_mvp/scheme.html?authority=Adur. This is a quick demo of some of these ideas -- the sidebar and toolbox both change when you're editing or drawing something. This is a rough sketch of this idea, but any thoughts on it? Is this worth pursuing?

**Comment by Robinlovelace** [comment]
Tried it. Really like it, way better on small screens and allows more focus on job at hand. Didn't detect any downside.

![image](https://github.com/acteng/atip/assets/1825120/375cc9b3-bfd8-44fe-9422-f5aff26d428d)

**Comment by dabreegster** [comment]
Edit modes merged a while ago
