### ISSUE TITLE
Improve route snapper functionality

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#25]
Currently there are issues of 'doubling up' after sketching and it's not immediately clear how to edit routes after snapping, e.g. to represent a yet-to-be-created segment on the network.

**Comment by Robinlovelace** [comment]
Heads-up @dabreegster I've marked this and a couple of other issues as bugs as a shorthand way of saying I think we need to fix these before putting this out there and saying it's ready to use: https://github.com/acteng/atip/labels/bug

**Comment by dabreegster** [comment]
https://github.com/stevage/mapbox-gl-draw/blob/snapping/src/snapping.js / https://github.com/mapbox/mapbox-gl-draw/issues/947 for other examples of this kind of plugin

**Comment by dabreegster** [comment]
The doubling back problem is now solved. After finishing snapping, it's just a regular mapbox-gl-draw linestring, which can be edited by clicking on the control points appropriately. It's not a great experience, but unless we go reinvent that drawing plugin, it'll have to be good enough for now. Instructions / tutorial can supplement

**Comment by Robinlovelace** [comment]
Amazing, this is sooo impressive. Just showed it to @mem48 and he was impressed.
