### ISSUE TITLE
Reduce coordinate precision

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#252]
Our output GeoJSON is unnecessarily large today with too many decimal places. GJ spec recommends fewer. We can get much smaller file sizes as a result. This should be a relatively straightforward fix to the draw tools in this repo, and another to route-snapper. We could also consider adding this to backfill scripts, though it doesn't seem too important.

https://github.com/perrygeo/geojson-precision has more context/examples. I don't think we need to depend on this package or any dependency to do the trimming, just listing it as reference

**Comment by dabreegster** [comment]
https://wiki.openstreetmap.org/wiki/Precision_of_coordinates for more reference

**Comment by robinlovelace-ate** [comment]
This should make ATIP files even smaller and snappier to share. Great work!
