### ISSUE TITLE
Adjust boundary data

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#264]
A few related tasks:

- [ ] Include Mayoral Combined Authorities (and another -- maybe LAs and not LADs? Re-reading Teams chats still)
- [ ] Fill in missing LADs (see below)
- [ ] Reduce coordinate precision in the GJ file to shrink it
- [ ] Add optional layers to scheme browsing page to show different authority boundaries
- [ ] Revisit using convex hull around boundaries to ensure the street network is connected for route-snapper

The missing LAD problem:
![Screenshot from 2023-07-11 12-42-45](https://github.com/acteng/atip/assets/1664407/ea7e80cb-86b2-46d3-a1cc-aa4fa29bb6db)
ATIP is using https://github.com/acteng/atip/blob/main/assets/authorities.geojson. This file comes from https://github.com/acteng/schema/blob/main/boundaries/lads_tas_combined.geojson, processed by https://github.com/acteng/abstreet-to-atip/tree/main/fix_boundaries. Checking another repo, I see https://github.com/acteng/boundaries/blob/main/lads.geojson, which looks complete to me. Should we use that file along with https://github.com/acteng/boundaries/blob/main/transport_authorities.geojson and ignore that old combined GJ file?

**Comment by dabreegster** [comment]
Revisiting https://github.com/acteng/abstreet-to-atip/issues/4#issuecomment-1419158941, checking different versions of the LPAs from OS...

BFC version (https://geoportal.statistics.gov.uk/datasets/ons::local-planning-authorities-april-2022-uk-bfc/explore?location=50.835262%2C-1.072888%2C15.49) has the same problem:
![Screenshot from 2023-07-11 12-54-42](https://github.com/acteng/atip/assets/1664407/864b793b-172f-4b74-a5c0-042581b707ad)

BGC also won't work: https://geoportal.statistics.gov.uk/datasets/ons::local-planning-authorities-april-2022-uk-bgc-3/explore?location=50.806798%2C-0.966544%2C12.44

Or BUC: https://geoportal.statistics.gov.uk/datasets/ons::local-planning-authorities-april-2022-uk-buc-3/explore?location=50.838586%2C-1.066440%2C12.95

But BFE (https://geoportal.statistics.gov.uk/datasets/ons::local-planning-authorities-april-2022-uk-bfe-3/explore?location=50.830575%2C-1.076023%2C13.60) looks good; it's just one polygon for Portsmouth! I think we need to switch to this geometry

**Comment by robinlovelace-ate** [comment]
Big +1 to this. My first impression is that just being able to view the boundaries would be enough.

**Comment by robinlovelace-ate** [comment]
> Checking another repo, I see https://github.com/acteng/boundaries/blob/main/lads.geojson, which looks complete to me. Should we use that file along with https://github.com/acteng/boundaries/blob/main/transport_authorities.geojson and ignore that old combined GJ file?

Yes but the file needs to be updated based on this newer LAD level data. Everything can be built from LADs.

**Comment by robinlovelace-ate** [comment]
https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-may-2023-uk-bfc-2/explore

**Comment by dabreegster** [comment]
After we change the boundaries file, I'll regenerate all route-snapper and route-info files. It's a slightly costly process, so let's batch together any changes and confirm them before proceeding. One concern is about backwards compatibility: any authority names defined by ATIP files built up to this point are based on the old boundaries. So if the newer files change anything substantial, we should understand it.

I'm still trying to detangle all the definitions of things from the chat yesterday... today we have:

- LADs, which could come from https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-may-2023-uk-bfc-2/explore
- TAs, which are composed of multiple LADs using a table in https://github.com/acteng/boundaries

And Chris linked to LPAs; the BFE version of that fixes the multi-polygon problem. Today we don't have LPAs; do we want them as well?

I can't find MCAs defined on that geoportal site either.

**Comment by robinlovelace-ate** [comment]
> Today we don't have LPAs; do we want them as well?

Yes I think so, a relevant boundary dataset.

**Comment by dabreegster** [comment]
Reading through https://geoportal.statistics.gov.uk/documents/boundary-dataset-guidance-2011-to-2021/explore and https://www.ons.gov.uk/methodology/geography/geographicalproducts/digitalboundaries closely... we want "extent of the realm" to avoid things like the Portsmouth issue. But the only variation available with this is BFE, which is full resolution. Just LADS with trimmed coordinate precision winds up 90MB. Do we have to make our own generalized extent of the realm variations?

**Comment by dabreegster** [comment]
If we want to revisit this and also fix #345, here's a new writeup. Ignore the rest of this issue; it was confusing other work for the browse page. This is just about the boundaries used on the start page for the sketch tool. It has:

- TAs, which are composed of multiple LADs using a table in https://github.com/acteng/boundaries
- LADs,  from a place like https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-may-2023-uk-bfc-2/explore

There are a few problems:

1) LADs that happen to share the same name with a TA are skipped. I'm not sure that's appropriate; we should include all of them? Or if the boundaries are exactly the same for those cases, we could mark it in the geojson as "both" with some property.
2) In London and Portsmouth and other places, the boundary is clipped to the coastline in ways that break the route tool. We need one simple polygon covering the whole area. Previously we've tried to fix this by taking a convex hull of the input, but it makes the boundaries overlap with each other and look messy, and it doesn't work for the Thames in London. I think we want "extent of the realm" variations, but also to keep resolution low or down-scale in order to keep file sizes small.

**Comment by dabreegster** [comment]
Consolidating in #345
