### ISSUE TITLE
Logistics before launch

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#27]
- [ ] Double check instructions and everything in the UI
- [ ] Get a new user to try everything out for real, for an entire real scheme
- [ ] Produce documentation / tutorial video

**Comment by dabreegster** [comment]
and productionization...

- [ ] unpkg
- [ ] maptiler API key
- [ ] deploy to S3

**Comment by dabreegster** [comment]
Hilariously, https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-custom-domain-walkthrough.html#add-bucket-policy-root-domain is wrong, the `resource` in the template policy is somehow wrong. Sigh.

**Comment by dabreegster** [comment]
I followed https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-custom-domain-walkthrough.html. `atip.uk` and `www.atip.uk` set up and work.

- need to deal with the `/atip/` base path
- need to set up cloudfront and HTTPS

**Comment by dabreegster** [comment]
OK, https://atip.uk/atip/index.html now working. Route snapper files moved over. Next problem is the `/atip/` base path. Needed for github deploy, not prod. I'll try getting Vite to override this again

**Comment by dabreegster** [comment]
Need to redirect HTTP to HTTPS and make /index.html the default path. Then the prod deployment will be pretty ready

**Comment by Robinlovelace** [comment]
Nice!
