### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#29]
- [ ] Clear cache to remove objects drawn in previous sessions, which seem to load in new windows, I just fired up a new window and had these objects sat there, how to remove?

![image](https://user-images.githubusercontent.com/1825120/202446476-0960a024-d14f-4fe2-853f-2dc12c9a071c.png)

- [ ] Slightly nicer aesthetics + padding, worthwhile if possible
- [ ] Instructions

**Comment by Robinlovelace** [comment]
> Would a trash can tool on the right help?

Yes, the problem with relying on clicking on unwanted objects is that they can be hard to find.

**Comment by Robinlovelace** [comment]
> Should we change the "Save" / "Delete" style in the bottom form to be more prominent?

Not sure, worth a try!

> Do you want a way to "clear" the entire map? The danger there is that the user might lose all their work, so maybe we need to prompt them first and remind them to save to geojson

Good point. A warning saying "Remove all data. Are you sure?" should solve that.

**Comment by dabreegster** [comment]
I've added a "Start over" button. Instructions and padding have also been improved, so closing this for now.
