### ISSUE TITLE
Changing basemap clears other layers

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#300]
As tested just now...

**Comment by dabreegster** [comment]
Yep, it resets all state on the browse page, including whatever file you've loaded. The trouble is that MapLibre doesn't distinguish the "basemap" sources + layers from the ones we add on top of it. Changing basemap clears out everything, so we have to carefully add back all the additional sources and layers. It's tough to code, so for now, we just reload the entire page from scratch and make the user re-enable things. It's fixable with moderate-high effort, but I wouldn't call it a priority.

**Comment by robinlovelace-ate** [comment]
Thanks Dustin, yes I recall from previous projects that basemaps are not a strength of MapLibre, and indeed https://actdev.cyipt.bike/lcid/routenetwork,buildings/#12.35/53.79066/-1.5235 has the same issue I think. Not a priority, known issue and hopeful of upstream fixes MapLibre side: surely loads of people hitting the same thing will motivate development their side.

**Comment by robinlovelace-ate** [comment]
Some of these seem relevant: https://github.com/search?q=repo%3Amaplibre%2Fmaplibre-gl-js+basemap&type=issues
