### ISSUE TITLE
DfT count layer

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#318]
Requested today. Click through to something like https://roadtraffic.dft.gov.uk/manualcountpoints/28512 maybe

**Comment by Robinlovelace** [comment]
Impressive! The DfT count data provides counts for road sections that have start and end points so can be visualised as linestrings, e.g.

![image](https://github.com/acteng/atip/assets/1825120/21ca2286-0a63-417c-b010-369cc5dbf6f6)

Source: https://bikedata.cyclestreets.net/collisions,trafficcounts/#14.14/53.83128/-1.57107

Problem with that: it fails to snap the link to the road.

**Comment by Robinlovelace** [comment]
Equivalent from ATIP:

![image](https://github.com/acteng/atip/assets/1825120/7d47c9da-4ac6-4459-985c-e8a2034f6b5d)


Source: https://acteng.github.io/atip/browse.html?authority=West%20Yorkshire%20Combined%20Authority#14.44/53.80831/-1.54725

**Comment by Robinlovelace** [comment]
If you look at the actual data from the DfT, accessible by clicking on the dot (great feature BTW), you can see it has start and end junction and link length attributes:

![image](https://github.com/acteng/atip/assets/1825120/e57617f6-0fff-44c5-a9ce-4ded43f29f1d)

Source: https://roadtraffic.dft.gov.uk/manualcountpoints/17374

**Comment by dabreegster** [comment]
If it'd be useful to show the linestring segment covered by the count, we could work on that, but we haven't had any feedback about the layer or how it's used yet

**Comment by Robinlovelace** [comment]
I recall seeing Easting/Northing data of junctions at one point, more relevant for cars than bikes, but not sure if they are available in the latest version of the data.

**Comment by Robinlovelace** [comment]
Worth asking if that would be useful. Hypothesis: yes.
