### ISSUE TITLE
Critical issue data entry

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#322]
Investigate short-term options for entering criticals.

Input fields are:
- scheme reference and design stage
- one of 15 criticals (and then there are sub-questions on some)
- freeform notes
- a lat, long
- name of nearest street / intersection

Last two are slightly tedious to generate.

We can focus on making a nice UI for doing this and punt on how we submit the data somewhere. I thought we might be able to open an MS Forms URL and attach query parameters to pre-fill some fields, but apparently this may not be supported -- still need to try. Even still, it's not throwaway work, since eventually we'll be able to submit to an API and stash in a proper DB.

**Comment by Pete-Y-CS** [comment]
Okay after discussion with Dustin we have agreed on some initial steps to implement then get feedback for iteration:

- At first we will implement a new page, which allows you to drop a pin then fill in a form.
- This will not be hooked up to any actual database or output, it's just in anticipation of scheme updater paving the way for us to have DB access
- You will be able to access this page directly, or by selecting a scheme on the scheme browse page, and the page will be opened centred on that scheme's location

A second stage of work will allow the user to see existing entered criticals, again not actually hooked up to a backend but demonstrating how it would work with a working DB integration
