### ISSUE TITLE
Pipeline attribute fields

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#355]
As discussed with Pete here's a draft schema for collecting schemes in the pipeline

### Scheme level attributes

- Scheme type
- Scheme name
- Scheme description
- Budget
- Status
- Timescale
- Funding programme

### Intervention level attributes

- Intervention type
- Intervention name
- Intervention description

More detailed version

<details>

### Scheme level attributes

- Scheme type
  - Options TBC
- Scheme name
- Scheme description
- Budget
    - To nearest 10k?
    - Based on current (2023) prices
- Status
  - Completed
  - Funded: Under construction
  - Funded: Construction not started
- Timescale
  - The categories here could depend on answers to previous question
  - For not started: financial year
  - For under construction or completed: date
- Funding programme targetted
  - No funding programme assigned
  - ATF
  - ...

### Intervention level attributes

- Intervention type
  - ATF4 categories
- Intervention name
- Intervention description

**Comment by dabreegster** [comment]
This is started, based on an internal data spec doc. Continuing to iterate on the specifics. Closing.
