### ISSUE TITLE
November prototype

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#4]
- [x] adjust the form contents for areas
- [x] add a delete button
- [x] add clickable map to intro page
- [x] start shell of pages for crossings and routes, links between all 3
- [x] add a "load from geojson file" button
- [x] auto-save changes to browser local storage (per authority and intervention type)
- [x] shop around for existing map{libre,box} snapping plugins or prototype something new
- [ ] stretch: add a button to the area tool to "prototype details in abstreet" (requires importing everywhere and snapping custom areas to blocks)

About the import from OSM / seeding initial data... they're quite large, but https://github.com/acteng/atip/blob/main/authorities.geojson does split things into boundaries. I could one-off import into A/B Street, then write something quick to export to ATIP. Crossings and LTN areas would be easy, routes much harder. Can also start to think about putting some of this directly on top of `osm2streets` instead of going all the way into A/B Street representation (which has extra detail and performance penalty for stuff with buildings, pathfinding that's unnecessary)

**Comment by Robinlovelace** [comment]
Sounds good, the form contents for the areas and minimal example that is not quite MVP but functional can be found here for inspiration: https://shiny.robinlovelace.net/atipshiny/

**Comment by dabreegster** [comment]
https://github.com/acteng/abstreet-to-atip started to seed ATIP with some initial data (for areas, at least). I'll think through the process for including this in the UI and for generating it...

**Comment by Robinlovelace** [comment]
Good topic for the hackathon!

**Comment by dabreegster** [comment]
I discovered people have already made a host of other plugins for drawing / editing stuff with mapbox! https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/MODES.md#available-custom-modes
Some of these, like "split linestring", could be great for cutting a long route into pieces and specifying width, segregation, etc per segment.

Next up:
- form contents
- get the route snapping tool merged in, even for one fixed area
- start coloring features to distinguish those that have their form filled out correctly/completely and those that're still TODO
- start a tool to "import from OSM" generically. just select the smaller area you want, then we'll fetch from overpass, pipe through osm2streets, and extract features appropriately. Can start something super simple for areas, routes, and crossings. For now, the user can click on imported features and use the "delete" tool to ignore them.

**Comment by dabreegster** [comment]
This issue is mostly done or unfocused, so closing

**Comment by Robinlovelace** [comment]
Belated big thumbs up on this :+1: :tada:
