### ISSUE TITLE
Route snapper tool behavior

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#43]
Separate tools for snapping to roads and drawing lines free-form aren't a good UX. We can have one tool that can optionally snap. First step is writing down exactly how that would work.

Strawman example:
- Neutral state: Click the tool to start. It's in snapping mode. Visually we show when we're close enough to a route start point.
- Snap preview state: Now as we move the mouse around, we show a preview of the route from the last waypoint to where the mouse is currently snapped. Clicking adds a waypoint to the end.
- Dragging state: if we hover over a point on the existing route drawn so far, we stop drawing the preview route from the last waypoint, and show that the point by the cursor can be dragged. The user can drag that, and we adjust the snapped route accordingly.
  - Problem: it's visually noisy and confusing to put the mouse near a point on the existing route, because we're constantly drawing a preview of the next step of the route.
- Freeform mode: the user presses and holds down the shift key. From the last waypoint they've drawn, we just preview a straight line until they click and add that waypoint. No routing between these two, and we draw this freeform line segment a little differently to emphasize it.
  - Problem: what if this new freeform endpoint is far away from the street network, but the user intends to resume snapping? Use case is a route that's on existing streets almost the whole way through, but cuts through a new park path or a new bridge somewhere in the middle.

We could indicate possible actions in the current state by adding some text to the tool's button. "Click near an intersection to start the route." "Click to add a waypoint." "Drag a blue point to adjust the route." "Hold shift to draw a straight line."

**Comment by dabreegster** [comment]
How does Felt work, as reference? It shares the first problem -- I get a previewed route as I move around, and only when I hover over part of the existing route does the preview go away. It's actually not visually obvious to me that I can drag part of the existing route.

Idea: we show blue dots today for every single draggable waypoint. They're too visually loud? We could draw them much more softly, or not at all. When the user hovers near the route, they appear to indicate draggable control points.

They have a decent answer to the second problem. If I hold shift and draw a straight line ending in the middle of a park or water, then let go of shift, I'm back in snapping mode. The last point isn't on the street network. So when I'm back in the default snapping mode, they search the entire route drawn so far in reverse and find the first point that's close enough to a street. The previewed path starts from there. The possible problem is that the entire drawn route can easily become discontinuous. ... Ah, but once I click and finalize the route, they just join the gap with a straight line. Kind of odd, but it works.

**Comment by dabreegster** [comment]
Example of a gap if I end a route in the middle of nowhere:
![Screenshot from 2022-11-25 10-27-47](https://user-images.githubusercontent.com/1664407/203963218-c4257642-1a4f-4371-9fea-77a200138a6e.png)
But they automatically fill it in:
![Screenshot from 2022-11-25 10-28-20](https://user-images.githubusercontent.com/1664407/203963270-ef11c15d-2dee-4997-aa2f-ed465a314607.png)

**Comment by Robinlovelace** [comment]
One tool to rule them all gets my vote! I think your plan sounds good and is worth giving it a bash, can always iterate after testing.

**Comment by dabreegster** [comment]
Closing as not actionable. Also, I'm in the middle of moving this to a separate repo, https://github.com/dabreegster/route_snapper. Any bugs/problems with the tool, please report there from now on

**Comment by Robinlovelace** [comment]
Great refactor and split-out mission!
