### ISSUE TITLE
Use Protomaps?

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#45]
From #5

**Comment by Robinlovelace** [comment]
Closing as not relevant at the moment.

**Comment by dabreegster** [comment]
Could we have a backlog label or something? I still want to consider this as an alternative to depending on MapTiler in production, and I'd like to have the discussion when more of the tech team is here

**Comment by robinlovelace-ate** [comment]
Sure, sorry for prematurely closing. That's what issues and tickets are there for!

**Comment by robinlovelace-ate** [comment]
Marked as 'wontfix' for now because, even though this may be worked on and fixed at some point, we're not planning to do anything for now. Any tweaks to Labels welcome.

**Comment by dabreegster** [comment]
We're using pmtiles in many places now
