### ISSUE TITLE
Cycle Parking on Browse Page not colour not distinct

### ISSUE THREAD

**Issue by Pete-Y-CS** [acteng/atip#476]
The black colour of dots for cycle parking is overloaded and not clear.

Yellow looks unused so for a first pass thinking of using that

**Comment by dabreegster** [comment]
We can use arbitrary symbols for points. See the `SymbolLayer` example in the latest PR. Time to try that for some of the point layers?

**Comment by dabreegster** [comment]
One option for symbols is the set used on the main OSM Carto renderer. The license looks fine.
https://wiki.openstreetmap.org/wiki/OpenStreetMap_Carto/Symbols
https://github.com/gravitystorm/openstreetmap-carto?tab=License-1-ov-file#readme
