### ISSUE TITLE
Make button to clear interventions more prominent and ... clear in its meaning

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#48]
Currently it's

![image](https://user-images.githubusercontent.com/1825120/205383029-94a87cfa-4e0b-49c0-b858-adeb8a7864b0.png)

Worth making that more prominent, e.g.:

**Clear all interventions**

?

**Comment by dabreegster** [comment]
I've been trying to match Figma. Longer text? Larger? An icon maybe?
https://www.figma.com/file/UbiKrnWEeQ5IXw4BTdVQwJ/ATIP-tool-draft?node-id=1%3A3&t=uSp7torEkeBeEKOg-0
![Screenshot from 2022-12-02 20-48-36](https://user-images.githubusercontent.com/1664407/205383858-b9ac09ff-2690-4a45-a584-cf6652e7badb.png)

**Comment by Robinlovelace** [comment]
I think maybe it's just because the text seems smaller than the n Interventions text? Less is more, think it's fine, minor question.
