### ISSUE TITLE
Features later

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#5]
As I work on the prototype, just writing down stuff I want to think about for later.

- Undo/redo, version history

**Comment by Robinlovelace** [comment]
That would be amazing. Keeping the UI small and simple in the first instance is important is one thought. Let's see how it evolves!

**Comment by dabreegster** [comment]
- Consider protomaps, if we don't want dependencies on maptiler or another tile host

**Comment by Robinlovelace** [comment]
Will split out into separate issues now.
