### ISSUE TITLE
Prototype SchoolRoutes layer

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#530]
Currently we have the PCT layer which provides good estimates of long-term cycling potential along key corridors, but is a bit out-of-date, does not provide good estimates in residential areas, has low mesh density and has nothing on walking.

The SchoolRoutes project will overcome some of these limitations. It would be great if we can get a demo of how to include the outputs in ATIP's browse tool. Good news: I come with test data, generated by `od2net`: https://github.com/acteng/netgen/releases/download/v0.1.0/output_pct_govtarget.pmtiles

**Comment by dabreegster** [comment]
When you have nationwide results you're happy with, it's quite easy for us to add a layer, sure :)

**Comment by Robinlovelace** [comment]
Ace. On me to generate them!
