### ISSUE TITLE
Perf: serve gzipped files

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#57]
For route snapper files, this would be great. There are headers, maybe S3 / Cloudfront can handle them

**Comment by dabreegster** [comment]
I'm marking this as v2, because it's pretty low-hanging fruit that I want to ship in the next version. It'll help initial loading times.

Need to modify the scripts in https://github.com/acteng/abstreet-to-atip/ to gzip stuff, upload the new files, change ATIP to load them, and figure out if the browser will automatically gunzip stuff for us or not.

**Comment by robinlovelace-ate** [comment]
I thought the route snapper used binary file format that was already compressed?

**Comment by robinlovelace-ate** [comment]
> It's a binary file, but uncompressed right now. This issue is to add gzip. I'll do benchmarks in the PR, but a quick sample of one file shows 12MB down to 4MB

Impressive compression! I associate 'binary' e.g. .pbf with compressed but seems that is not always the case, binaries may also have big potential for compression by the looks, off topic but would be interested to know what's in the binary, but that's just for personal interest ; )

**Comment by dabreegster** [comment]
The route snapper is mostly a bunch of floating point numbers: https://github.com/dabreegster/route_snapper/blob/main/route-snapper-graph/src/lib.rs

osm2streets has a bunch of stuff: https://github.com/a-b-street/osm2streets/blob/0d6f0f973b3fa8dbdc8223aa6f412a8d997252fc/osm2streets/src/lib.rs#L47

Both serialize using https://serde.rs/ with the bincode format

**Comment by dabreegster** [comment]
Route snapper files: total 960MB down to 690MB.

Route info: 5.8GB down to 2.2GB!

**Comment by dabreegster** [comment]
Fixed by 5690e8c237d119df73b41fc8e636c8788f3cfa9a

**Comment by robinlovelace-ate** [comment]
Impressive, huge win for responsiveness and computer resources!
