### ISSUE TITLE
Format instructions

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#60]
Currently they are not divided into bullet points or even paragraphs with a decent amount of room between each para:

![image](https://user-images.githubusercontent.com/1825120/210872161-7e2dd44d-23a6-4559-a43c-4e44277ed75f.png)

This makes them hard to read/absorb.

**Comment by dabreegster** [comment]
![Screenshot from 2023-01-06 09-35-22](https://user-images.githubusercontent.com/1664407/210973383-fa146792-dce5-4401-99f4-438e5d1735da.png)
Slight improvement, but worse than before we adapted carbon-components-svelte.onrender.com/. I can't figure out why its styles break the paragraph tag! There are enough issues with this design system, going to try [one of the many others](https://www.youtube.com/watch?v=O0mNU0maItY) later.

Still need to rewrite the contents of the instructions

**Comment by Robinlovelace** [comment]
Should be possible to just write Markdown and it should work, no?

**Comment by Robinlovelace** [comment]
Improvement for sure.

**Comment by dabreegster** [comment]
> Should be possible to just write Markdown and it should work, no?

No, unless you're using something specifically that translates to HTML. The problem is just that the Carbon design system I pulled in breaks basic HTML styling of paragraphs and lists. I made the wrong choice between the ~dozen out there, will try others.

**Comment by dabreegster** [comment]
This is just explaining how to contribute documentation, which they write in Markdown. Bit of a moot point, I don't think Carbon is appropriate for us to keep using.

**Comment by Robinlovelace** [comment]
Sorry, yes, my bad.

**Comment by Robinlovelace** [comment]
Agreed, still not ideal. Will mark as help wanted... Latest version same as above:

![image](https://user-images.githubusercontent.com/1825120/222837356-c04b22b7-e961-4f34-8887-c9a2dcec5930.png)

**Comment by dabreegster** [comment]
This was fixed when we migrated off Carbon:
![Screenshot from 2023-05-19 12-45-32](https://github.com/acteng/atip/assets/1664407/93603ace-30f8-40a4-b1e8-28591cc85354)
#116 remains open -- we need to completely rewrite the instructions
