### ISSUE TITLE
Submitting a random string on the home page select LAD box returns a blank map 

### ISSUE THREAD

**Issue by Sparrow0hawk** [acteng/atip#71]
Whilst looking through the log data I saw a couple of entries that didn't match available LADs and Transport authorities on the app.

It looks like some users might type in their authority and hit `Start` without selecting from the presented drop-down.

E.g. https://atip.uk/scheme.html?authority=narnia#1/0/0 

<img width="1512" alt="Screenshot 2023-02-08 at 11 32 21" src="https://user-images.githubusercontent.com/20887250/217518339-3cb1d166-34a8-4fac-b62f-7a6a42e1fc1b.png">

## Steps to reproduce

1. Visit https://atip.uk/index.html
2. In the `Select Transport Authority or Local Authority District:` box enter your own random string
3. Click Start

## Suggested fix

I think we'd want to see if we could write in some user validation at the select step, just to make sure they are constrained to available LADs/authorities.

**Comment by dabreegster** [comment]
Good catch! Should be an easy fix. https://github.com/acteng/atip/blob/84e37a50e25f111c1a6ab2003347db3609b33397/ChooseArea.svelte#L92 is when the button click happens, we can check the input is in the GeoJSON set (or maybe even in the data-list element we already made)
