### ISSUE TITLE
Cannot draw route through boundary

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#79]
See screenshot here: https://imgur.com/a/2YpHQH1

https://atip.uk/scheme.html?authority=West%20Midlands%20ITA#11.89/52.57591/-1.82034

**Comment by robinlovelace-ate** [comment]
This is a demo issue to encourage others to post issues. Will aim to describe the solution in the next comment in case anyone is hitting this issue.

**Comment by robinlovelace-ate** [comment]
Solution: press the Shift key while on the Route Snapper tool to draw the infrastructure outside the boundary. This is related to #73 and we're not planning to make any changes to the tool around this for now but can keep this issue open in case anyone is hitting it and wondering. Known issue/feature!

**Comment by dabreegster** [comment]
New route tool UI makes it even easier to mix free/snapped points, and the boundary area is easy to see
