### ISSUE TITLE
File upload to SmartSurvey problem

### ISSUE THREAD

**Issue by sarahellwood** [acteng/atip#82]
Error message when upoading to Smart Survey: 'there was a problem uploading your file' 

![image](https://user-images.githubusercontent.com/125486470/219085451-fff9c651-0746-4150-b784-59d148d9209c.png)

**Comment by robinlovelace-ate** [comment]
> Error message when upoading to Smart Survey: 'there was a problem uploading your file'
> 
> ![image](https://user-images.githubusercontent.com/125486470/219085451-fff9c651-0746-4150-b784-59d148d9209c.png)

Thanks for the feedback @sarahellwood does it give any more detail on what the problem was? I don't think it's something that can be solved by changes to ATIP. As a test could you try uploading a .txt file that was *not* created with ATIP. If you get the same message that indicates that it may be an issue with the system.

**Comment by sarahellwood** [comment]
Thanks Robin. I tried another .txt file and got the same error message: 
![image](https://user-images.githubusercontent.com/125486470/219321223-75304395-bd99-4999-88ca-832f72160f12.png)

The red error bar appears from left to right, stays for around one second then vanishes. I will ask a colleague to try.

**Comment by robinlovelace-ate** [comment]
Thanks for trying again and for confirming that the form does not allow any .txt files, created by ATIP or any other software, to be uploaded from your computer. I suspect this is a temporary glitch or perhaps specific to your network. Please send an email to the generic support address and others with more knowledge of the issue can respond. Do keep us posted and good luck.
