### ISSUE TITLE
Port to TypeScript

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#89]
I'm uncomfortable writing increasingly large/complex software, which'll have multiple contributors, in a language without static types. But so far I've used TypeScript myself very little, and hit a number of snags with it, over in https://github.com/dabreegster/osm2svelte. Do we have any TypeScript experience on the incoming team? I'd like to have a discussion over how soon we should get used to using it, and what to watch out for.

**Comment by Robinlovelace** [comment]
All good questions, one for Slack, let's ask and nudge people this coming week.

**Comment by Sparrow0hawk** [comment]
Interesting counter point to typescript is maybe just using JSDocs.

This is how they do it with SvelteKit - https://www.reddit.com/r/sveltejs/comments/1219z04/thoughts_on_this_twitter_thread_svelte_and_ts/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

I don't have a particular dog in this fight (have already started looking at TS anyway).

**Comment by dabreegster** [comment]
Close when we've enabled strict mode (no implicit anys, no nulls)

**Comment by dabreegster** [comment]
https://github.com/gcanti/newtype-ts looking at this
