### ISSUE TITLE
Reconsider Carbon

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#90]
I chose [Carbon](https://carbon-components-svelte.onrender.com/) as a Svelte component library pretty early on, after trying other options only very briefly. I have a few small complaints about it so far (the stylesheet makes regular HTML defaults look less usable, so for example in `components/Instructions.svelte` we had to switch to their `OrderedList` and `ListItem` components).

Also, will we be required to use https://design-system.service.gov.uk/, and if so, how soon?

**Comment by Robinlovelace** [comment]
> Also, will we be required to use https://design-system.service.gov.uk/, and if so, how soon?

Depends how quickly we want to submit Alpha. Around July is a very rough estimate.

**Comment by dabreegster** [comment]
There's no documented way to tell a https://carbon-components-svelte.onrender.com/components/Modal to be larger?! If there's embedded content that expands/contracts, it's not smart at all about handling a max size.
![Screenshot from 2023-03-27 10-24-03](https://user-images.githubusercontent.com/1664407/227900391-6e7d1cc5-38aa-417f-b206-2054c3d80e62.png)

There is no great reason for us to stick with Carbon, very eager to find something else

**Comment by dabreegster** [comment]
Aaaaand just noticing this beauty:
![Screenshot from 2023-03-27 15-59-14](https://user-images.githubusercontent.com/1664407/227979644-d0d16ca1-68f1-4cd9-81aa-3190bb63d460.png)
When we hide the sidebar, all the buttons and text and stuff correctly disappears and isn't interactive. But the Carbon accordions are still there and clickable

**Comment by dabreegster** [comment]
Another issue I just noticed: the Carbon package isn't hermetic; we're reaching out to the network:
![Screenshot from 2023-04-12 12-01-08](https://user-images.githubusercontent.com/1664407/231438319-79feb8c8-b7a3-4b5c-891d-ef5460dc80e4.png)

**Comment by dabreegster** [comment]
If we can put together our own modal popup element, we're pretty much rid of this
